/* 
 * This file was generated by T4 - do not edit.
 * Contains constants for strongly typed views in controllers.
 * Directories (may be nested) are static class names, views are constant strings.
 */

namespace League.ViewNames
{
    public static class Account
    {
        public const string ConfirmEmailError = "ConfirmEmailError";
        public const string CreateAccount = "CreateAccount";
        public const string ExternalSignInConfirmation = "ExternalSignInConfirmation";
        public const string ExternalSignInFailure = "ExternalSignInFailure";
        public const string ForgotPassword = "ForgotPassword";
        public const string ForgotPasswordConfirmation = "ForgotPasswordConfirmation";
        public const string PleaseConfirmEmail = "PleaseConfirmEmail";
        public const string Register = "Register";
        public const string ResetPassword = "ResetPassword";
        public const string ResetPasswordConfirmation = "ResetPasswordConfirmation";
        public const string SignIn = "SignIn";
        public const string SignInRejected = "SignInRejected";
        public const string SignInRejectedEmailNotConfirmed = "SignInRejectedEmailNotConfirmed";
    }
    public static class Error
    {
        public const string AccessDenied = "AccessDenied";
        public const string Index = "Index";
    }
    public static class Home
    {
        public const string AboutLeague = "AboutLeague";
        public const string AboutLeaguede = "AboutLeague.de";
        public const string Contact = "Contact";
        public const string ContactConfirmation = "ContactConfirmation";
        public const string LegalDisclosure = "LegalDisclosure";
        public const string LegalDisclosurede = "LegalDisclosure.de";
        public const string Overview = "Overview";
        public const string PictureCredits = "PictureCredits";
        public const string Privacy = "Privacy";
        public const string Privacyde = "Privacy.de";
        public const string Welcome = "Welcome";
    }
    public static class Manage
    {
        public const string Index = "Index";
        public const string _ChangeEmailModalPartial = "_ChangeEmailModalPartial";
        public const string _ChangePasswordModalPartial = "_ChangePasswordModalPartial";
        public const string _ChangeUsernameModalPartial = "_ChangeUsernameModalPartial";
        public const string _DeleteAccountModalPartial = "_DeleteAccountModalPartial";
        public const string _EditEmail2ModalPartial = "_EditEmail2ModalPartial";
        public const string _EditPersonalDetailsModalPartial = "_EditPersonalDetailsModalPartial";
        public const string _EditPhone2ModalPartial = "_EditPhone2ModalPartial";
        public const string _EditPhoneModalPartial = "_EditPhoneModalPartial";
        public const string _IndexMessagesPartial = "_IndexMessagesPartial";
        public const string _ManageLoginsModalPartial = "_ManageLoginsModalPartial";
        public const string _SetPasswordModalPartial = "_SetPasswordModalPartial";
    }
    public static class Map
    {
        public const string Index = "Index";
    }
    public static class Match
    {
        public const string EditFixture = "EditFixture";
        public const string EnterResult = "EnterResult";
        public const string EnterResultNotAllowed = "EnterResultNotAllowed";
        public const string Fixtures = "Fixtures";
        public const string ReportSheet = "ReportSheet";
        public const string Results = "Results";
        public const string _FixtureMessagesPartial = "_FixtureMessagesPartial";
        public const string _ResultMessagesPartial = "_ResultMessagesPartial";
    }
    public static class Organization
    {
        public static class a_beach
        {
            public static class Home
            {
                public const string Index = "Index";
            }
            public static class Info
            {
                public const string News = "News";
                public const string RuleOfGame = "RuleOfGame";
            }
        }
        public static class a_indoor
        {
            public static class Home
            {
                public const string Index = "Index";
            }
            public static class Info
            {
                public const string News = "News";
                public const string RuleOfGame = "RuleOfGame";
            }
        }
        public static class OtherOrg
        {
            public static class Home
            {
                public const string Index = "Index";
            }
        }
        public static class TestOrg
        {
            public static class Home
            {
                public const string Index = "Index";
            }
        }
    }
    public static class Ranking
    {
        public const string AllTimeForTeam = "AllTimeForTeam";
        public const string AllTimeForTournament = "AllTimeForTournament";
        public const string Table = "Table";
    }
    public static class Role
    {
        public const string _AddMemberModalPartial = "_AddMemberModalPartial";
        public const string _RemoveMemberModalPartial = "_RemoveMemberModalPartial";
    }
    public static class Shared
    {
        public const string NavigationNodeChildDropdownPartial = "NavigationNodeChildDropdownPartial";
        public const string NavigationNodeChildTreePartial = "NavigationNodeChildTreePartial";
        public const string NavigationNodeSideNavPartial = "NavigationNodeSideNavPartial";
        public const string _DateTimePickerScriptPartial = "_DateTimePickerScriptPartial";
        public const string _FavIcons = "_FavIcons";
        public const string _GoogleAnalyticsScriptsPartial = "_GoogleAnalyticsScriptsPartial";
        public const string _LanguagePartial = "_LanguagePartial";
        public const string _Layout = "_Layout";
        public const string _passwordRules = "_passwordRules";
        public const string _ValidationScriptsPartial = "_ValidationScriptsPartial";
        public static class Components
        {
            public static class Navigation
            {
                public const string BootstrapBreadcrumbs = "BootstrapBreadcrumbs";
                public const string BootstrapTopNav = "BootstrapTopNav";
                public const string BootstrapTopNavWithDropdowns = "BootstrapTopNavWithDropdowns";
                public const string ChildTree = "ChildTree";
                public const string Default = "Default";
                public const string SideNav = "SideNav";
                public const string SiteMap = "SiteMap";
            }
            public static class RoundSelector
            {
                public const string Default = "Default";
            }
            public static class TeamEditor
            {
                public const string Default = "Default";
            }
            public static class VenueEditor
            {
                public const string Default = "Default";
            }
            public static class VenueSelector
            {
                public const string Default = "Default";
            }
        }
    }
    public static class Team
    {
        public const string List = "List";
        public const string MyTeam = "MyTeam";
        public const string MyTeamNotFound = "MyTeamNotFound";
        public const string Single = "Single";
        public const string _ChangeVenueModalPartial = "_ChangeVenueModalPartial";
        public const string _EditTeamModalPartial = "_EditTeamModalPartial";
        public const string _MyTeamMessagesPartial = "_MyTeamMessagesPartial";
        public const string _SelectVenueModalPartial = "_SelectVenueModalPartial";
    }
    public static class TeamApplication
    {
        public const string Confirm = "Confirm";
        public const string EditTeam = "EditTeam";
        public const string EditVenue = "EditVenue";
        public const string List = "List";
        public const string SelectTeam = "SelectTeam";
        public const string SelectVenue = "SelectVenue";
        public const string Start = "Start";
        public const string Startde = "Start.de";
        public const string _TeamApplicationMessagesPartial = "_TeamApplicationMessagesPartial";
    }
    public static class Upload
    {
        public const string TeamPhoto = "TeamPhoto";
    }
    public static class Venue
    {
        public const string EditVenue = "EditVenue";
    }
    public static class Area
    {
        public static class Admin
        {
            public const string _ViewImports = "_ViewImports";
            public const string _ViewStart = "_ViewStart";
            public static class Impersonation
            {
                public const string Index = "Index";
            }
            public static class Shared
            {
                public const string _Layout = "_Layout";
            }
            public static class System
            {
                public const string ShowClaims = "ShowClaims";
            }
        }
    }
}