//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League.Models.ErrorViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("League.Models.ErrorViewModels.StatusDescriptions", typeof(StatusDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request.
        /// </summary>
        public static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are performing some maintenance. Please try again in a few minutes.
        /// </summary>
        public static string E2 {
            get {
                return ResourceManager.GetString("E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested resource was not found.
        /// </summary>
        public static string E404 {
            get {
                return ResourceManager.GetString("E404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A server side error occured.
        /// </summary>
        public static string E500 {
            get {
                return ResourceManager.GetString("E500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header values specify a configuration that is not implemented.
        /// </summary>
        public static string E501 {
            get {
                return ResourceManager.GetString("E501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad server or proxy response.
        /// </summary>
        public static string E502 {
            get {
                return ResourceManager.GetString("E502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required service is not available.
        /// </summary>
        public static string E503 {
            get {
                return ResourceManager.GetString("E503", resourceCulture);
            }
        }
    }
}
