//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace TournamentManager.DAL.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'CompletedMatch'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="TournamentManager.DAL.FactoryClasses.QueryFactory.CompletedMatch"/>. </remarks>
	[Serializable]
	public partial class CompletedMatchRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="CompletedMatchRow"/> class.</summary>
		public CompletedMatchRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the GuestBallPoints field.</summary>
		public Nullable<System.Int32> GuestBallPoints { get; set; }
		/// <summary>Gets or sets the GuestMatchPoints field.</summary>
		public Nullable<System.Int32> GuestMatchPoints { get; set; }
		/// <summary>Gets or sets the GuestSetPoints field.</summary>
		public Nullable<System.Int32> GuestSetPoints { get; set; }
		/// <summary>Gets or sets the GuestTeamId field.</summary>
		public System.Int64 GuestTeamId { get; set; }
		/// <summary>Gets or sets the GuestTeamNameForRound field.</summary>
		public System.String GuestTeamNameForRound { get; set; }
		/// <summary>Gets or sets the HomeBallPoints field.</summary>
		public Nullable<System.Int32> HomeBallPoints { get; set; }
		/// <summary>Gets or sets the HomeMatchPoints field.</summary>
		public Nullable<System.Int32> HomeMatchPoints { get; set; }
		/// <summary>Gets or sets the HomeSetPoints field.</summary>
		public Nullable<System.Int32> HomeSetPoints { get; set; }
		/// <summary>Gets or sets the HomeTeamId field.</summary>
		public System.Int64 HomeTeamId { get; set; }
		/// <summary>Gets or sets the HomeTeamNameForRound field.</summary>
		public System.String HomeTeamNameForRound { get; set; }
		/// <summary>Gets or sets the Id field.</summary>
		public System.Int64 Id { get; set; }
		/// <summary>Gets or sets the IsOverruled field.</summary>
		public System.Boolean IsOverruled { get; set; }
		/// <summary>Gets or sets the MatchDate field.</summary>
		public Nullable<System.DateTime> MatchDate { get; set; }
		/// <summary>Gets or sets the ModifiedOn field.</summary>
		public System.DateTime ModifiedOn { get; set; }
		/// <summary>Gets or sets the Remarks field.</summary>
		public System.String Remarks { get; set; }
		/// <summary>Gets or sets the RoundDescription field.</summary>
		public System.String RoundDescription { get; set; }
		/// <summary>Gets or sets the RoundId field.</summary>
		public System.Int64 RoundId { get; set; }
		/// <summary>Gets or sets the RoundLegDescription field.</summary>
		public System.String RoundLegDescription { get; set; }
		/// <summary>Gets or sets the RoundLegSequenceNo field.</summary>
		public System.Int32 RoundLegSequenceNo { get; set; }
		/// <summary>Gets or sets the RoundName field.</summary>
		public System.String RoundName { get; set; }
		/// <summary>Gets or sets the RoundTypeDescription field.</summary>
		public System.String RoundTypeDescription { get; set; }
		/// <summary>Gets or sets the RoundTypeName field.</summary>
		public System.String RoundTypeName { get; set; }
		/// <summary>Gets or sets the SetResults field.</summary>
		public System.String SetResults { get; set; }
		/// <summary>Gets or sets the TournamentId field.</summary>
		public Nullable<System.Int64> TournamentId { get; set; }
		/// <summary>Gets or sets the TournamentName field.</summary>
		public System.String TournamentName { get; set; }
		/// <summary>Gets or sets the VenueId field.</summary>
		public Nullable<System.Int64> VenueId { get; set; }
	}
}

