//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace TournamentManager.DAL.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'TeamVenueRound'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="TournamentManager.DAL.FactoryClasses.QueryFactory.TeamVenueRound"/>. </remarks>
	[Serializable]
	public partial class TeamVenueRoundRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TeamVenueRoundRow"/> class.</summary>
		public TeamVenueRoundRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the MatchDayOfWeek field.</summary>
		public Nullable<System.Int32> MatchDayOfWeek { get; set; }
		/// <summary>Gets or sets the MatchTime field.</summary>
		public Nullable<System.TimeSpan> MatchTime { get; set; }
		/// <summary>Gets or sets the MatchWeekday field.</summary>
		public System.String MatchWeekday { get; set; }
		/// <summary>Gets or sets the RoundDescription field.</summary>
		public System.String RoundDescription { get; set; }
		/// <summary>Gets or sets the RoundId field.</summary>
		public System.Int64 RoundId { get; set; }
		/// <summary>Gets or sets the RoundName field.</summary>
		public System.String RoundName { get; set; }
		/// <summary>Gets or sets the RoundTypeDescription field.</summary>
		public System.String RoundTypeDescription { get; set; }
		/// <summary>Gets or sets the RoundTypeName field.</summary>
		public System.String RoundTypeName { get; set; }
		/// <summary>Gets or sets the TeamClubName field.</summary>
		public System.String TeamClubName { get; set; }
		/// <summary>Gets or sets the TeamId field.</summary>
		public System.Int64 TeamId { get; set; }
		/// <summary>Gets or sets the TeamModifiedOn field.</summary>
		public System.DateTime TeamModifiedOn { get; set; }
		/// <summary>Gets or sets the TeamName field.</summary>
		public System.String TeamName { get; set; }
		/// <summary>Gets or sets the TeamNameForRound field.</summary>
		public System.String TeamNameForRound { get; set; }
		/// <summary>Gets or sets the TournamentId field.</summary>
		public System.Int64 TournamentId { get; set; }
		/// <summary>Gets or sets the VenueCity field.</summary>
		public System.String VenueCity { get; set; }
		/// <summary>Gets or sets the VenueDirection field.</summary>
		public System.String VenueDirection { get; set; }
		/// <summary>Gets or sets the VenueId field.</summary>
		public Nullable<System.Int64> VenueId { get; set; }
		/// <summary>Gets or sets the VenueLatitude field.</summary>
		public Nullable<System.Double> VenueLatitude { get; set; }
		/// <summary>Gets or sets the VenueLongitude field.</summary>
		public Nullable<System.Double> VenueLongitude { get; set; }
		/// <summary>Gets or sets the VenueModifiedOn field.</summary>
		public Nullable<System.DateTime> VenueModifiedOn { get; set; }
		/// <summary>Gets or sets the VenueName field.</summary>
		public System.String VenueName { get; set; }
		/// <summary>Gets or sets the VenuePostalCode field.</summary>
		public System.String VenuePostalCode { get; set; }
		/// <summary>Gets or sets the VenuePrecisePosition field.</summary>
		public Nullable<System.Boolean> VenuePrecisePosition { get; set; }
		/// <summary>Gets or sets the VenueStreet field.</summary>
		public System.String VenueStreet { get; set; }
	}
}

