//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.Adapter;

namespace TournamentManager.DAL.DatabaseSpecific
{
	/// <summary>Class which contains the static logic to execute retrieval stored procedures in the database.</summary>
	public static partial class RetrievalProcedures
	{
		/// <summary>Gets the SP Call using query for fetching the VenueDistanceResult TypedView.</summary>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <returns>ready to use IRetrievalQuery instance for fetching the typedview</returns>
		/// <remarks>Output parameters are not set after query is executed</remarks>
		public static IRetrievalQuery GetQueryForVenueDistanceResultTypedView(System.Double maxDistance, System.Double lat, System.Double lng)
		{
			IRetrievalQuery query = GetVenueDistanceCallAsQuery(maxDistance, lat, lng);
			query.ResultsetNumber = 1;
			return query;
		}

		/// <summary>Fetches instances of the the typed view row 'VenueDistanceResultRow' class using a stored procedure call. </summary>
		/// <typeparam name="T">The type of the typed view row</typeparam>
		/// <param name="projectionOfTypedView">The projection of the typed view, created using the method QueryFactory.GetVenueDistanceResultTypedViewProjection().</param>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <returns>The results in a List</returns>
		public static List<T> FetchVenueDistanceResultTypedView<T>(SD.LLBLGen.Pro.QuerySpec.DynamicQuery<T> projectionOfTypedView, System.Double maxDistance, System.Double lat, System.Double lng)
		{
			using(var adapter = new DataAccessAdapter())
			{
				return FetchVenueDistanceResultTypedView(adapter, projectionOfTypedView, maxDistance, lat, lng);
			}
		}

		/// <summary>Fetches instances of the the typed view row 'VenueDistanceResultRow' class using a stored procedure call. </summary>
		/// <typeparam name="T">The type of the typed view row</typeparam>
		/// <param name="adapter">The adapter.</param>
		/// <param name="projectionOfTypedView">The projection of the typed view, created using the method QueryFactory.GetVenueDistanceResultTypedViewProjection().</param>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <returns>The results in a List</returns>
		public static List<T> FetchVenueDistanceResultTypedView<T>(IDataAccessAdapter adapter, SD.LLBLGen.Pro.QuerySpec.DynamicQuery<T> projectionOfTypedView, System.Double maxDistance, System.Double lat, System.Double lng)
		{
			StoredProcedureCall call = CreateVenueDistanceCall(adapter, maxDistance, lat, lng);
			IRetrievalQuery query = call.ToRetrievalQuery();
			query.ResultsetNumber = 1;
			var toReturn = adapter.FetchQueryFromSource(projectionOfTypedView, query);
			return toReturn;
		}
		
		/// <summary>Fetches instances of the the typed view row 'VenueDistanceResultRow' class using a stored procedure call. Async variant</summary>
		/// <typeparam name="T">The type of the typed view row</typeparam>
		/// <param name="projectionOfTypedView">The projection of the typed view, created using the method QueryFactory.GetVenueDistanceResultTypedViewProjection().</param>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <param name="cancellationToken">The cancellation token to use</param>
		/// <returns>The results in a list.</returns>
		public static async Task<List<T>> FetchVenueDistanceResultTypedViewAsync<T>(SD.LLBLGen.Pro.QuerySpec.DynamicQuery<T> projectionOfTypedView, System.Double maxDistance, System.Double lat, System.Double lng, CancellationToken cancellationToken)
		{
			using(var adapter = new DataAccessAdapter())
			{
				var toReturn = await FetchVenueDistanceResultTypedViewAsync(adapter, projectionOfTypedView, maxDistance, lat, lng, cancellationToken).ConfigureAwait(false);
				return toReturn;
			}
		}

		/// <summary>Fetches instances of the the typed view row 'VenueDistanceResultRow' class using a stored procedure call. Async variant </summary>
		/// <typeparam name="T">The type of the typed view row</typeparam>
		/// <param name="adapter">The adapter.</param>
		/// <param name="projectionOfTypedView">The projection of the typed view, created using the method QueryFactory.GetVenueDistanceResultTypedViewProjection().</param>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <param name="cancellationToken">The cancellation token to use</param>
		/// <returns>The results in a list.</returns>
		public static async Task<List<T>> FetchVenueDistanceResultTypedViewAsync<T>(IDataAccessAdapter adapter, SD.LLBLGen.Pro.QuerySpec.DynamicQuery<T> projectionOfTypedView, System.Double maxDistance, System.Double lat, System.Double lng, CancellationToken cancellationToken)
		{
			var call = CreateVenueDistanceCall(adapter, maxDistance, lat, lng);
			var query = call.ToRetrievalQuery();
			query.ResultsetNumber = 1;
			var typedView = await adapter.FetchQueryFromSourceAsync(projectionOfTypedView, query, cancellationToken).ConfigureAwait(false);
			return typedView;
		}


		/// <summary>Calls stored procedure 'VenueDistance'.<br/><br/></summary>
		/// <param name="maxDistance">Input parameter. </param>
		/// <param name="lat">Input parameter. </param>
		/// <param name="lng">Input parameter. </param>
		/// <returns>Filled DataTable with resultset(s) of stored procedure</returns>
		public static DataTable VenueDistance(System.Double maxDistance, System.Double lat, System.Double lng)
		{
			using(var dataAccessProvider = new DataAccessAdapter())
			{
				return VenueDistance(maxDistance, lat, lng, dataAccessProvider);
			}
		}

		/// <summary>Calls stored procedure 'VenueDistance'.<br/><br/></summary>
		/// <param name="dataAccessProvider">The data access provider.</param>
		/// <param name="maxDistance">Input parameter. </param>
		/// <param name="lat">Input parameter. </param>
		/// <param name="lng">Input parameter. </param>
		/// <returns>Filled DataTable with resultset(s) of stored procedure</returns>
		public static DataTable VenueDistance(System.Double maxDistance, System.Double lat, System.Double lng, IDataAccessCore dataAccessProvider)
		{
			using(StoredProcedureCall call = CreateVenueDistanceCall(dataAccessProvider, maxDistance, lat, lng))
			{
				DataTable toReturn = call.FillDataTable();
				return toReturn;
			}
		}

		/// <summary>Creates an IRetrievalQuery object for a call to the procedure 'VenueDistance'.</summary>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <returns>IRetrievalQuery object which is ready to use for datafetching</returns>
		public static IRetrievalQuery GetVenueDistanceCallAsQuery(System.Double maxDistance, System.Double lat, System.Double lng)
		{
			using(var dataAccessProvider = new DataAccessAdapter())
			{
				return GetVenueDistanceCallAsQuery(maxDistance, lat, lng, dataAccessProvider);
			}
		}

		/// <summary>Creates an IRetrievalQuery object for a call to the procedure 'VenueDistance'.</summary>
		/// <param name="maxDistance">Input parameter of stored procedure</param>
		/// <param name="lat">Input parameter of stored procedure</param>
		/// <param name="lng">Input parameter of stored procedure</param>
		/// <param name="dataAccessProvider">The data access provider.</param>
		/// <returns>IRetrievalQuery object which is ready to use for datafetching</returns>
		public static IRetrievalQuery GetVenueDistanceCallAsQuery(System.Double maxDistance, System.Double lat, System.Double lng, IDataAccessCore dataAccessProvider)
		{
			return CreateVenueDistanceCall(dataAccessProvider, maxDistance, lat, lng).ToRetrievalQuery();
		}

		/// <summary>Creates the call object for the call 'VenueDistance' to stored procedure 'VenueDistance'.</summary>
		/// <param name="dataAccessProvider">The data access provider.</param>
		/// <param name="maxDistance">Input parameter</param>
		/// <param name="lat">Input parameter</param>
		/// <param name="lng">Input parameter</param>
		/// <returns>Ready to use StoredProcedureCall object</returns>
		private static StoredProcedureCall CreateVenueDistanceCall(IDataAccessCore dataAccessProvider, System.Double maxDistance, System.Double lat, System.Double lng)
		{
			return new StoredProcedureCall(dataAccessProvider, @"[TestOrg].[dbo].[VenueDistance]", "VenueDistance")
							.AddParameter("@MaxDistance", "Float", 0, ParameterDirection.Input, true, 38, 0, maxDistance)
							.AddParameter("@Lat", "Float", 0, ParameterDirection.Input, true, 38, 0, lat)
							.AddParameter("@Lng", "Float", 0, ParameterDirection.Input, true, 38, 0, lng);
		}


	}
}
