//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using TournamentManager.DAL.FactoryClasses;
using TournamentManager.DAL.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace TournamentManager.DAL.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitAvailableMatchDateEntityInfo();
			InitExcludeMatchDateEntityInfo();
			InitIdentityRoleEntityInfo();
			InitIdentityRoleClaimEntityInfo();
			InitIdentityUserClaimEntityInfo();
			InitIdentityUserLoginEntityInfo();
			InitIdentityUserRoleEntityInfo();
			InitIdentityUserTokenEntityInfo();
			InitManagerOfTeamEntityInfo();
			InitMatchEntityInfo();
			InitMatchRuleEntityInfo();
			InitPlayerInTeamEntityInfo();
			InitRankingEntityInfo();
			InitRegistrationEntityInfo();
			InitRoundEntityInfo();
			InitRoundLegEntityInfo();
			InitRoundTypeEntityInfo();
			InitSetEntityInfo();
			InitSetRuleEntityInfo();
			InitTeamEntityInfo();
			InitTeamInRoundEntityInfo();
			InitTournamentEntityInfo();
			InitTournamentTypeEntityInfo();
			InitUserEntityInfo();
			InitVenueEntityInfo();
			InitCalendarTypedViewInfo();
			InitCompletedMatchTypedViewInfo();
			InitLatestTeamTournamentTypedViewInfo();
			InitMatchCompleteRawTypedViewInfo();
			InitMatchReportSheetTypedViewInfo();
			InitMatchToPlayRawTypedViewInfo();
			InitPlannedMatchTypedViewInfo();
			InitRankingListTypedViewInfo();
			InitRoundLegPeriodTypedViewInfo();
			InitRoundTeamTypedViewInfo();
			InitTeamUserRoundTypedViewInfo();
			InitTeamVenueRoundTypedViewInfo();
			InitVenueDistanceResultTypedViewInfo();
			InitVenueTeamTypedViewInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits AvailableMatchDateEntity's info objects</summary>
		private void InitAvailableMatchDateEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(AvailableMatchDateFieldIndex), "AvailableMatchDateEntity");
			this.AddElementFieldInfo("AvailableMatchDateEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)AvailableMatchDateFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "TournamentId", typeof(System.Int64), false, false, false, false,  (int)AvailableMatchDateFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "HomeTeamId", typeof(System.Int64), false, true, false, false,  (int)AvailableMatchDateFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "VenueId", typeof(System.Int64), false, true, false, false,  (int)AvailableMatchDateFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "MatchStartTime", typeof(System.DateTime), false, false, false, false,  (int)AvailableMatchDateFieldIndex.MatchStartTime, 0, 0, 0);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "MatchEndTime", typeof(System.DateTime), false, false, false, false,  (int)AvailableMatchDateFieldIndex.MatchEndTime, 0, 0, 0);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "IsGenerated", typeof(System.Boolean), false, false, false, false,  (int)AvailableMatchDateFieldIndex.IsGenerated, 0, 0, 0);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)AvailableMatchDateFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("AvailableMatchDateEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)AvailableMatchDateFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits ExcludeMatchDateEntity's info objects</summary>
		private void InitExcludeMatchDateEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ExcludeMatchDateFieldIndex), "ExcludeMatchDateEntity");
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)ExcludeMatchDateFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "TournamentId", typeof(System.Int64), false, true, false, false,  (int)ExcludeMatchDateFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "RoundId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)ExcludeMatchDateFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "TeamId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)ExcludeMatchDateFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "DateFrom", typeof(System.DateTime), false, false, false, false,  (int)ExcludeMatchDateFieldIndex.DateFrom, 0, 0, 0);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "DateTo", typeof(System.DateTime), false, false, false, false,  (int)ExcludeMatchDateFieldIndex.DateTo, 0, 0, 0);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "Reason", typeof(System.String), false, false, false, true,  (int)ExcludeMatchDateFieldIndex.Reason, 60, 0, 0);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)ExcludeMatchDateFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("ExcludeMatchDateEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)ExcludeMatchDateFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits IdentityRoleEntity's info objects</summary>
		private void InitIdentityRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityRoleFieldIndex), "IdentityRoleEntity");
			this.AddElementFieldInfo("IdentityRoleEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)IdentityRoleFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityRoleEntity", "Name", typeof(System.String), false, false, false, false,  (int)IdentityRoleFieldIndex.Name, 255, 0, 0);
		}

		/// <summary>Inits IdentityRoleClaimEntity's info objects</summary>
		private void InitIdentityRoleClaimEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityRoleClaimFieldIndex), "IdentityRoleClaimEntity");
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "ClaimType", typeof(System.String), false, false, false, false,  (int)IdentityRoleClaimFieldIndex.ClaimType, 255, 0, 0);
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "ClaimValue", typeof(System.String), false, false, false, false,  (int)IdentityRoleClaimFieldIndex.ClaimValue, 2147483647, 0, 0);
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)IdentityRoleClaimFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "Issuer", typeof(System.String), false, false, false, true,  (int)IdentityRoleClaimFieldIndex.Issuer, 255, 0, 0);
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "RoleId", typeof(System.Int64), false, true, false, false,  (int)IdentityRoleClaimFieldIndex.RoleId, 0, 0, 19);
			this.AddElementFieldInfo("IdentityRoleClaimEntity", "ValueType", typeof(System.String), false, false, false, true,  (int)IdentityRoleClaimFieldIndex.ValueType, 255, 0, 0);
		}

		/// <summary>Inits IdentityUserClaimEntity's info objects</summary>
		private void InitIdentityUserClaimEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityUserClaimFieldIndex), "IdentityUserClaimEntity");
			this.AddElementFieldInfo("IdentityUserClaimEntity", "ClaimType", typeof(System.String), false, false, false, false,  (int)IdentityUserClaimFieldIndex.ClaimType, 255, 0, 0);
			this.AddElementFieldInfo("IdentityUserClaimEntity", "ClaimValue", typeof(System.String), false, false, false, false,  (int)IdentityUserClaimFieldIndex.ClaimValue, 2147483647, 0, 0);
			this.AddElementFieldInfo("IdentityUserClaimEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)IdentityUserClaimFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserClaimEntity", "Issuer", typeof(System.String), false, false, false, true,  (int)IdentityUserClaimFieldIndex.Issuer, 255, 0, 0);
			this.AddElementFieldInfo("IdentityUserClaimEntity", "UserId", typeof(System.Int64), false, true, false, false,  (int)IdentityUserClaimFieldIndex.UserId, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserClaimEntity", "ValueType", typeof(System.String), false, false, false, true,  (int)IdentityUserClaimFieldIndex.ValueType, 255, 0, 0);
		}

		/// <summary>Inits IdentityUserLoginEntity's info objects</summary>
		private void InitIdentityUserLoginEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityUserLoginFieldIndex), "IdentityUserLoginEntity");
			this.AddElementFieldInfo("IdentityUserLoginEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)IdentityUserLoginFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserLoginEntity", "LoginProvider", typeof(System.String), true, false, false, false,  (int)IdentityUserLoginFieldIndex.LoginProvider, 128, 0, 0);
			this.AddElementFieldInfo("IdentityUserLoginEntity", "ProviderDisplayName", typeof(System.String), false, false, false, false,  (int)IdentityUserLoginFieldIndex.ProviderDisplayName, 128, 0, 0);
			this.AddElementFieldInfo("IdentityUserLoginEntity", "ProviderKey", typeof(System.String), true, false, false, false,  (int)IdentityUserLoginFieldIndex.ProviderKey, 128, 0, 0);
			this.AddElementFieldInfo("IdentityUserLoginEntity", "UserId", typeof(System.Int64), true, true, false, false,  (int)IdentityUserLoginFieldIndex.UserId, 0, 0, 19);
		}

		/// <summary>Inits IdentityUserRoleEntity's info objects</summary>
		private void InitIdentityUserRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityUserRoleFieldIndex), "IdentityUserRoleEntity");
			this.AddElementFieldInfo("IdentityUserRoleEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)IdentityUserRoleFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserRoleEntity", "RoleId", typeof(System.Int64), true, true, false, false,  (int)IdentityUserRoleFieldIndex.RoleId, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserRoleEntity", "UserId", typeof(System.Int64), true, true, false, false,  (int)IdentityUserRoleFieldIndex.UserId, 0, 0, 19);
		}

		/// <summary>Inits IdentityUserTokenEntity's info objects</summary>
		private void InitIdentityUserTokenEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(IdentityUserTokenFieldIndex), "IdentityUserTokenEntity");
			this.AddElementFieldInfo("IdentityUserTokenEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)IdentityUserTokenFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserTokenEntity", "LoginProvider", typeof(System.String), true, false, false, false,  (int)IdentityUserTokenFieldIndex.LoginProvider, 128, 0, 0);
			this.AddElementFieldInfo("IdentityUserTokenEntity", "Name", typeof(System.String), true, false, false, false,  (int)IdentityUserTokenFieldIndex.Name, 128, 0, 0);
			this.AddElementFieldInfo("IdentityUserTokenEntity", "UserId", typeof(System.Int64), true, true, false, false,  (int)IdentityUserTokenFieldIndex.UserId, 0, 0, 19);
			this.AddElementFieldInfo("IdentityUserTokenEntity", "Value", typeof(System.String), false, false, false, true,  (int)IdentityUserTokenFieldIndex.Value, 2147483647, 0, 0);
		}

		/// <summary>Inits ManagerOfTeamEntity's info objects</summary>
		private void InitManagerOfTeamEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ManagerOfTeamFieldIndex), "ManagerOfTeamEntity");
			this.AddElementFieldInfo("ManagerOfTeamEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)ManagerOfTeamFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("ManagerOfTeamEntity", "UserId", typeof(System.Int64), true, true, false, false,  (int)ManagerOfTeamFieldIndex.UserId, 0, 0, 19);
			this.AddElementFieldInfo("ManagerOfTeamEntity", "TeamId", typeof(System.Int64), true, true, false, false,  (int)ManagerOfTeamFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("ManagerOfTeamEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)ManagerOfTeamFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("ManagerOfTeamEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)ManagerOfTeamFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits MatchEntity's info objects</summary>
		private void InitMatchEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MatchFieldIndex), "MatchEntity");
			this.AddElementFieldInfo("MatchEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)MatchFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "HomeTeamId", typeof(System.Int64), false, true, false, false,  (int)MatchFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "GuestTeamId", typeof(System.Int64), false, true, false, false,  (int)MatchFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "RefereeId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)MatchFieldIndex.RefereeId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "RoundId", typeof(System.Int64), false, true, false, false,  (int)MatchFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "VenueId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)MatchFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "OrigVenueId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)MatchFieldIndex.OrigVenueId, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "LegSequenceNo", typeof(Nullable<System.Int32>), false, false, false, true,  (int)MatchFieldIndex.LegSequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("MatchEntity", "HomePoints", typeof(Nullable<System.Int32>), false, false, false, true,  (int)MatchFieldIndex.HomePoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchEntity", "GuestPoints", typeof(Nullable<System.Int32>), false, false, false, true,  (int)MatchFieldIndex.GuestPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchEntity", "IsComplete", typeof(System.Boolean), false, false, false, false,  (int)MatchFieldIndex.IsComplete, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "IsOverruled", typeof(System.Boolean), false, false, false, false,  (int)MatchFieldIndex.IsOverruled, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "PlannedStart", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.PlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "PlannedEnd", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.PlannedEnd, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "OrigPlannedStart", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.OrigPlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "OrigPlannedEnd", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.OrigPlannedEnd, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "RealStart", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.RealStart, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "RealEnd", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)MatchFieldIndex.RealEnd, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)MatchFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "ChangeSerial", typeof(System.Int64), false, false, false, false,  (int)MatchFieldIndex.ChangeSerial, 0, 0, 19);
			this.AddElementFieldInfo("MatchEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)MatchFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("MatchEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)MatchFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits MatchRuleEntity's info objects</summary>
		private void InitMatchRuleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MatchRuleFieldIndex), "MatchRuleEntity");
			this.AddElementFieldInfo("MatchRuleEntity", "BestOf", typeof(System.Boolean), false, false, false, false,  (int)MatchRuleFieldIndex.BestOf, 0, 0, 0);
			this.AddElementFieldInfo("MatchRuleEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)MatchRuleFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("MatchRuleEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)MatchRuleFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("MatchRuleEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)MatchRuleFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("MatchRuleEntity", "Name", typeof(System.String), false, false, false, false,  (int)MatchRuleFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("MatchRuleEntity", "NumOfSets", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.NumOfSets, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "PointsMatchLost", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.PointsMatchLost, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "PointsMatchLostAfterTieBreak", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.PointsMatchLostAfterTieBreak, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "PointsMatchTie", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.PointsMatchTie, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "PointsMatchWon", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.PointsMatchWon, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "PointsMatchWonAfterTieBreak", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.PointsMatchWonAfterTieBreak, 0, 0, 10);
			this.AddElementFieldInfo("MatchRuleEntity", "RankComparer", typeof(System.Int32), false, false, false, false,  (int)MatchRuleFieldIndex.RankComparer, 0, 0, 10);
		}

		/// <summary>Inits PlayerInTeamEntity's info objects</summary>
		private void InitPlayerInTeamEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PlayerInTeamFieldIndex), "PlayerInTeamEntity");
			this.AddElementFieldInfo("PlayerInTeamEntity", "Id", typeof(System.Int64), false, false, false, false,  (int)PlayerInTeamFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("PlayerInTeamEntity", "UserId", typeof(System.Int64), true, true, false, false,  (int)PlayerInTeamFieldIndex.UserId, 0, 0, 19);
			this.AddElementFieldInfo("PlayerInTeamEntity", "TeamId", typeof(System.Int64), true, true, false, false,  (int)PlayerInTeamFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("PlayerInTeamEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)PlayerInTeamFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("PlayerInTeamEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)PlayerInTeamFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RankingEntity's info objects</summary>
		private void InitRankingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RankingFieldIndex), "RankingEntity");
			this.AddElementFieldInfo("RankingEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)RankingFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("RankingEntity", "TournamentId", typeof(System.Int64), false, true, false, false,  (int)RankingFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("RankingEntity", "RoundId", typeof(System.Int64), false, true, false, false,  (int)RankingFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("RankingEntity", "TeamId", typeof(System.Int64), false, true, false, false,  (int)RankingFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("RankingEntity", "ValuationDate", typeof(System.DateTime), false, false, false, false,  (int)RankingFieldIndex.ValuationDate, 0, 0, 0);
			this.AddElementFieldInfo("RankingEntity", "Rank", typeof(System.Int32), false, false, false, false,  (int)RankingFieldIndex.Rank, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "MatchPointsWon", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.MatchPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "MatchPointsLost", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.MatchPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "SetPointsWon", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.SetPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "SetPointsLost", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.SetPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "BallPointsWon", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.BallPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "BallPointsLost", typeof(Nullable<System.Int32>), false, false, false, true,  (int)RankingFieldIndex.BallPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "MatchesPlayed", typeof(System.Int32), false, false, false, false,  (int)RankingFieldIndex.MatchesPlayed, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "MatchesToPlay", typeof(System.Int32), false, false, false, false,  (int)RankingFieldIndex.MatchesToPlay, 0, 0, 10);
			this.AddElementFieldInfo("RankingEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)RankingFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("RankingEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)RankingFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RegistrationEntity's info objects</summary>
		private void InitRegistrationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RegistrationFieldIndex), "RegistrationEntity");
			this.AddElementFieldInfo("RegistrationEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)RegistrationFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("RegistrationEntity", "TournamentId", typeof(System.Int64), false, true, false, false,  (int)RegistrationFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("RegistrationEntity", "TeamId", typeof(System.Int64), false, true, false, false,  (int)RegistrationFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("RegistrationEntity", "ManagerId", typeof(System.Int64), false, true, false, false,  (int)RegistrationFieldIndex.ManagerId, 0, 0, 19);
			this.AddElementFieldInfo("RegistrationEntity", "Guid", typeof(System.String), false, false, false, false,  (int)RegistrationFieldIndex.Guid, 50, 0, 0);
			this.AddElementFieldInfo("RegistrationEntity", "AppliedWithMessage", typeof(System.String), false, false, false, true,  (int)RegistrationFieldIndex.AppliedWithMessage, 4000, 0, 0);
			this.AddElementFieldInfo("RegistrationEntity", "AppliedOn", typeof(System.DateTime), false, false, false, false,  (int)RegistrationFieldIndex.AppliedOn, 0, 0, 0);
		}

		/// <summary>Inits RoundEntity's info objects</summary>
		private void InitRoundEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoundFieldIndex), "RoundEntity");
			this.AddElementFieldInfo("RoundEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)RoundFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "TournamentId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)RoundFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "Name", typeof(System.String), false, false, false, false,  (int)RoundFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("RoundEntity", "Description", typeof(System.String), false, false, false, false,  (int)RoundFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("RoundEntity", "TypeId", typeof(System.Int64), false, true, false, false,  (int)RoundFieldIndex.TypeId, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "NumOfLegs", typeof(System.Int32), false, false, false, false,  (int)RoundFieldIndex.NumOfLegs, 0, 0, 10);
			this.AddElementFieldInfo("RoundEntity", "MatchRuleId", typeof(System.Int64), false, true, false, false,  (int)RoundFieldIndex.MatchRuleId, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "SetRuleId", typeof(System.Int64), false, true, false, false,  (int)RoundFieldIndex.SetRuleId, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "IsComplete", typeof(System.Boolean), false, false, false, false,  (int)RoundFieldIndex.IsComplete, 0, 0, 0);
			this.AddElementFieldInfo("RoundEntity", "NextRoundId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)RoundFieldIndex.NextRoundId, 0, 0, 19);
			this.AddElementFieldInfo("RoundEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("RoundEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RoundLegEntity's info objects</summary>
		private void InitRoundLegEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoundLegFieldIndex), "RoundLegEntity");
			this.AddElementFieldInfo("RoundLegEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)RoundLegFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("RoundLegEntity", "RoundId", typeof(System.Int64), false, true, false, false,  (int)RoundLegFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("RoundLegEntity", "SequenceNo", typeof(System.Int32), false, false, false, false,  (int)RoundLegFieldIndex.SequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("RoundLegEntity", "Description", typeof(System.String), false, false, false, true,  (int)RoundLegFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("RoundLegEntity", "StartDateTime", typeof(System.DateTime), false, false, false, false,  (int)RoundLegFieldIndex.StartDateTime, 0, 0, 0);
			this.AddElementFieldInfo("RoundLegEntity", "EndDateTime", typeof(System.DateTime), false, false, false, false,  (int)RoundLegFieldIndex.EndDateTime, 0, 0, 0);
			this.AddElementFieldInfo("RoundLegEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundLegFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("RoundLegEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundLegFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RoundTypeEntity's info objects</summary>
		private void InitRoundTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoundTypeFieldIndex), "RoundTypeEntity");
			this.AddElementFieldInfo("RoundTypeEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)RoundTypeFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("RoundTypeEntity", "Name", typeof(System.String), false, false, false, false,  (int)RoundTypeFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("RoundTypeEntity", "Description", typeof(System.String), false, false, false, false,  (int)RoundTypeFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("RoundTypeEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundTypeFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("RoundTypeEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)RoundTypeFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits SetEntity's info objects</summary>
		private void InitSetEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SetFieldIndex), "SetEntity");
			this.AddElementFieldInfo("SetEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)SetFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("SetEntity", "MatchId", typeof(System.Int64), false, true, false, false,  (int)SetFieldIndex.MatchId, 0, 0, 19);
			this.AddElementFieldInfo("SetEntity", "SequenceNo", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.SequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "HomeBallPoints", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.HomeBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "GuestBallPoints", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.GuestBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "HomeSetPoints", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.HomeSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "GuestSetPoints", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.GuestSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "HomeTimeout", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.HomeTimeout, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "GuestTimeout", typeof(System.Int32), false, false, false, false,  (int)SetFieldIndex.GuestTimeout, 0, 0, 10);
			this.AddElementFieldInfo("SetEntity", "IsOverruled", typeof(System.Boolean), false, false, false, false,  (int)SetFieldIndex.IsOverruled, 0, 0, 0);
			this.AddElementFieldInfo("SetEntity", "IsTieBreak", typeof(System.Boolean), false, false, false, false,  (int)SetFieldIndex.IsTieBreak, 0, 0, 0);
			this.AddElementFieldInfo("SetEntity", "RealStart", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SetFieldIndex.RealStart, 0, 0, 0);
			this.AddElementFieldInfo("SetEntity", "RealEnd", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SetFieldIndex.RealEnd, 0, 0, 0);
			this.AddElementFieldInfo("SetEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)SetFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("SetEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)SetFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("SetEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)SetFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits SetRuleEntity's info objects</summary>
		private void InitSetRuleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SetRuleFieldIndex), "SetRuleEntity");
			this.AddElementFieldInfo("SetRuleEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)SetRuleFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("SetRuleEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)SetRuleFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("SetRuleEntity", "MaxSubstitutions", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.MaxSubstitutions, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "MaxTimeouts", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.MaxTimeouts, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)SetRuleFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("SetRuleEntity", "Name", typeof(System.String), false, false, false, false,  (int)SetRuleFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("SetRuleEntity", "NumOfPointsToWinRegular", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.NumOfPointsToWinRegular, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "NumOfPointsToWinTiebreak", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.NumOfPointsToWinTiebreak, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "PointsDiffToWinRegular", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.PointsDiffToWinRegular, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "PointsDiffToWinTiebreak", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.PointsDiffToWinTiebreak, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "PointsSetLost", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.PointsSetLost, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "PointsSetTie", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.PointsSetTie, 0, 0, 10);
			this.AddElementFieldInfo("SetRuleEntity", "PointsSetWon", typeof(System.Int32), false, false, false, false,  (int)SetRuleFieldIndex.PointsSetWon, 0, 0, 10);
		}

		/// <summary>Inits TeamEntity's info objects</summary>
		private void InitTeamEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TeamFieldIndex), "TeamEntity");
			this.AddElementFieldInfo("TeamEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)TeamFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("TeamEntity", "VenueId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)TeamFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("TeamEntity", "Name", typeof(System.String), false, false, false, false,  (int)TeamFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("TeamEntity", "MatchDayOfWeek", typeof(Nullable<System.Int32>), false, false, false, true,  (int)TeamFieldIndex.MatchDayOfWeek, 0, 0, 10);
			this.AddElementFieldInfo("TeamEntity", "MatchTime", typeof(Nullable<System.TimeSpan>), false, false, false, true,  (int)TeamFieldIndex.MatchTime, 0, 0, 0);
			this.AddElementFieldInfo("TeamEntity", "ClubName", typeof(System.String), false, false, false, true,  (int)TeamFieldIndex.ClubName, 255, 0, 0);
			this.AddElementFieldInfo("TeamEntity", "PhotoFilename", typeof(System.String), false, false, false, true,  (int)TeamFieldIndex.PhotoFilename, 255, 0, 0);
			this.AddElementFieldInfo("TeamEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)TeamFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)TeamFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits TeamInRoundEntity's info objects</summary>
		private void InitTeamInRoundEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TeamInRoundFieldIndex), "TeamInRoundEntity");
			this.AddElementFieldInfo("TeamInRoundEntity", "Id", typeof(System.Int64), false, false, true, false,  (int)TeamInRoundFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("TeamInRoundEntity", "RoundId", typeof(System.Int64), true, true, false, false,  (int)TeamInRoundFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("TeamInRoundEntity", "TeamId", typeof(System.Int64), true, true, false, false,  (int)TeamInRoundFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("TeamInRoundEntity", "TeamNameForRound", typeof(System.String), false, false, false, true,  (int)TeamInRoundFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("TeamInRoundEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)TeamInRoundFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamInRoundEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)TeamInRoundFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits TournamentEntity's info objects</summary>
		private void InitTournamentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TournamentFieldIndex), "TournamentEntity");
			this.AddElementFieldInfo("TournamentEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)TournamentFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("TournamentEntity", "Name", typeof(System.String), false, false, false, false,  (int)TournamentFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("TournamentEntity", "Description", typeof(System.String), false, false, false, true,  (int)TournamentFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("TournamentEntity", "TypeId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)TournamentFieldIndex.TypeId, 0, 0, 19);
			this.AddElementFieldInfo("TournamentEntity", "IsComplete", typeof(System.Boolean), false, false, false, false,  (int)TournamentFieldIndex.IsComplete, 0, 0, 0);
			this.AddElementFieldInfo("TournamentEntity", "IsPlanningMode", typeof(System.Boolean), false, false, false, false,  (int)TournamentFieldIndex.IsPlanningMode, 0, 0, 0);
			this.AddElementFieldInfo("TournamentEntity", "NextTournamentId", typeof(Nullable<System.Int64>), false, true, false, true,  (int)TournamentFieldIndex.NextTournamentId, 0, 0, 19);
			this.AddElementFieldInfo("TournamentEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)TournamentFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("TournamentEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)TournamentFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits TournamentTypeEntity's info objects</summary>
		private void InitTournamentTypeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TournamentTypeFieldIndex), "TournamentTypeEntity");
			this.AddElementFieldInfo("TournamentTypeEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)TournamentTypeFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("TournamentTypeEntity", "Name", typeof(System.String), false, false, false, false,  (int)TournamentTypeFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("TournamentTypeEntity", "Description", typeof(System.String), false, false, false, false,  (int)TournamentTypeFieldIndex.Description, 255, 0, 0);
			this.AddElementFieldInfo("TournamentTypeEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)TournamentTypeFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("TournamentTypeEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)TournamentTypeFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("UserEntity", "Guid", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Guid, 50, 0, 0);
			this.AddElementFieldInfo("UserEntity", "UserName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.UserName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PasswordHash", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PasswordHash, 2147483647, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Email", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "EmailConfirmedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.EmailConfirmedOn, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PhoneNumber", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PhoneNumber, 40, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PhoneNumberConfirmedOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.PhoneNumberConfirmedOn, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastLoginOn", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LastLoginOn, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "AccessFailedCount", typeof(System.Int32), false, false, false, false,  (int)UserFieldIndex.AccessFailedCount, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "LockoutEndDateUtc", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.LockoutEndDateUtc, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Gender", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Gender, 1, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Title", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Title, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.FirstName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "MiddleName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.MiddleName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastName", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.LastName, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Nickname", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Nickname, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PhoneNumber2", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PhoneNumber2, 40, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Email2", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Email2, 100, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Birthday", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)UserFieldIndex.Birthday, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "PhotoFilename", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.PhotoFilename, 255, 0, 0);
			this.AddElementFieldInfo("UserEntity", "DoNotContact", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.DoNotContact, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Remarks", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.Remarks, 4000, 0, 0);
			this.AddElementFieldInfo("UserEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits VenueEntity's info objects</summary>
		private void InitVenueEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VenueFieldIndex), "VenueEntity");
			this.AddElementFieldInfo("VenueEntity", "Id", typeof(System.Int64), true, false, true, false,  (int)VenueFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("VenueEntity", "Name", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "Extension", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.Extension, 255, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "Street", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.Street, 255, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "PostalCode", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.PostalCode, 10, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "City", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "Longitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)VenueFieldIndex.Longitude, 0, 0, 38);
			this.AddElementFieldInfo("VenueEntity", "Latitude", typeof(Nullable<System.Double>), false, false, false, true,  (int)VenueFieldIndex.Latitude, 0, 0, 38);
			this.AddElementFieldInfo("VenueEntity", "Direction", typeof(System.String), false, false, false, false,  (int)VenueFieldIndex.Direction, 2147483647, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "CreatedOn", typeof(System.DateTime), false, false, false, false,  (int)VenueFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "ModifiedOn", typeof(System.DateTime), false, false, false, false,  (int)VenueFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("VenueEntity", "PrecisePosition", typeof(System.Boolean), false, false, false, false,  (int)VenueFieldIndex.PrecisePosition, 0, 0, 0);
		}

		/// <summary>Inits CalendarView's info objects</summary>
		private void InitCalendarTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CalendarFieldIndex), "CalendarTypedView");
			this.AddElementFieldInfo("CalendarTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)CalendarFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)CalendarFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)CalendarFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)CalendarFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "HomeTeamNameForRound", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.HomeTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)CalendarFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "GuestTeamNameForRound", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.GuestTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "PlannedStart", typeof(Nullable<System.DateTime>), false, false, true, false, (int)CalendarFieldIndex.PlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "PlannedEnd", typeof(Nullable<System.DateTime>), false, false, true, false, (int)CalendarFieldIndex.PlannedEnd, 0, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)CalendarFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "VenueName", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenueName, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenueExtension", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenueExtension, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenueStreet", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenueStreet, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenuePostalCode", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenuePostalCode, 10, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenueCity", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenueCity, 255, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "VenueLongitude", typeof(Nullable<System.Double>), false, false, true, false, (int)CalendarFieldIndex.VenueLongitude, 0, 0, 38);
			this.AddElementFieldInfo("CalendarTypedView", "VenueLatitude", typeof(Nullable<System.Double>), false, false, true, false, (int)CalendarFieldIndex.VenueLatitude, 0, 0, 38);
			this.AddElementFieldInfo("CalendarTypedView", "VenueDirection", typeof(System.String), false, false, true, false, (int)CalendarFieldIndex.VenueDirection, 2147483647, 0, 0);
			this.AddElementFieldInfo("CalendarTypedView", "ChangeSerial", typeof(System.Int64), false, false, true, false, (int)CalendarFieldIndex.ChangeSerial, 0, 0, 19);
			this.AddElementFieldInfo("CalendarTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)CalendarFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits CompletedMatchView's info objects</summary>
		private void InitCompletedMatchTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CompletedMatchFieldIndex), "CompletedMatchTypedView");
			this.AddElementFieldInfo("CompletedMatchTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)CompletedMatchFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)CompletedMatchFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)CompletedMatchFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundLegSequenceNo", typeof(System.Int32), false, false, true, false, (int)CompletedMatchFieldIndex.RoundLegSequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "RoundLegDescription", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.RoundLegDescription, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)CompletedMatchFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "HomeTeamNameForRound", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.HomeTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)CompletedMatchFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "GuestTeamNameForRound", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.GuestTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)CompletedMatchFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("CompletedMatchTypedView", "MatchDate", typeof(Nullable<System.DateTime>), false, false, true, false, (int)CompletedMatchFieldIndex.MatchDate, 0, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "HomeMatchPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.HomeMatchPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "GuestMatchPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.GuestMatchPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "HomeSetPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.HomeSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "GuestSetPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.GuestSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "HomeBallPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.HomeBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "GuestBallPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)CompletedMatchFieldIndex.GuestBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("CompletedMatchTypedView", "SetResults", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.SetResults, 2147483647, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "IsOverruled", typeof(System.Boolean), false, false, true, false, (int)CompletedMatchFieldIndex.IsOverruled, 0, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "Remarks", typeof(System.String), false, false, true, false, (int)CompletedMatchFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("CompletedMatchTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)CompletedMatchFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits LatestTeamTournamentView's info objects</summary>
		private void InitLatestTeamTournamentTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(LatestTeamTournamentFieldIndex), "LatestTeamTournamentTypedView");
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TournamentId", typeof(System.Int64), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TournamentDescription", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TournamentDescription, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)LatestTeamTournamentFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamClubName", typeof(System.String), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamClubName, 255, 0, 0);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamMatchDayOfWeek", typeof(Nullable<System.Int32>), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamMatchDayOfWeek, 0, 0, 10);
			this.AddElementFieldInfo("LatestTeamTournamentTypedView", "TeamMatchTime", typeof(Nullable<System.TimeSpan>), false, false, true, false, (int)LatestTeamTournamentFieldIndex.TeamMatchTime, 0, 0, 0);
		}

		/// <summary>Inits MatchCompleteRawView's info objects</summary>
		private void InitMatchCompleteRawTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MatchCompleteRawFieldIndex), "MatchCompleteRawTypedView");
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)MatchCompleteRawFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)MatchCompleteRawFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)MatchCompleteRawFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)MatchCompleteRawFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)MatchCompleteRawFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)MatchCompleteRawFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "MatchDate", typeof(Nullable<System.DateTime>), false, false, true, false, (int)MatchCompleteRawFieldIndex.MatchDate, 0, 0, 0);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "HomeMatchPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.HomeMatchPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "GuestMatchPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.GuestMatchPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "HomeSetPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.HomeSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "GuestSetPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.GuestSetPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "HomeBallPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.HomeBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "GuestBallPoints", typeof(Nullable<System.Int32>), false, false, true, false, (int)MatchCompleteRawFieldIndex.GuestBallPoints, 0, 0, 10);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "IsOverruled", typeof(System.Boolean), false, false, true, false, (int)MatchCompleteRawFieldIndex.IsOverruled, 0, 0, 0);
			this.AddElementFieldInfo("MatchCompleteRawTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)MatchCompleteRawFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits MatchReportSheetView's info objects</summary>
		private void InitMatchReportSheetTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MatchReportSheetFieldIndex), "MatchReportSheetTypedView");
			this.AddElementFieldInfo("MatchReportSheetTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)MatchReportSheetFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)MatchReportSheetFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundLegSequenceNo", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundLegSequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "RoundLegDescription", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.RoundLegDescription, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)MatchReportSheetFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "HomeTeamNameForRound", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.HomeTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)MatchReportSheetFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "GuestTeamNameForRound", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.GuestTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "PlannedStart", typeof(Nullable<System.DateTime>), false, false, true, false, (int)MatchReportSheetFieldIndex.PlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "OrigPlannedStart", typeof(Nullable<System.DateTime>), false, false, true, false, (int)MatchReportSheetFieldIndex.OrigPlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "NumOfSets", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.NumOfSets, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "BestOf", typeof(System.Boolean), false, false, true, false, (int)MatchReportSheetFieldIndex.BestOf, 0, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "NumOfPointsToWinRegular", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.NumOfPointsToWinRegular, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "NumOfPointsToWinTieBreak", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.NumOfPointsToWinTieBreak, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "MaxTimeouts", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.MaxTimeouts, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "MaxSubstitutions", typeof(System.Int32), false, false, true, false, (int)MatchReportSheetFieldIndex.MaxSubstitutions, 0, 0, 10);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "ChangeSerial", typeof(System.Int64), false, false, true, false, (int)MatchReportSheetFieldIndex.ChangeSerial, 0, 0, 19);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "Remarks", typeof(System.String), false, false, true, false, (int)MatchReportSheetFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("MatchReportSheetTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)MatchReportSheetFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits MatchToPlayRawView's info objects</summary>
		private void InitMatchToPlayRawTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(MatchToPlayRawFieldIndex), "MatchToPlayRawTypedView");
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)MatchToPlayRawFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)MatchToPlayRawFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)MatchToPlayRawFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)MatchToPlayRawFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)MatchToPlayRawFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)MatchToPlayRawFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "MatchDate", typeof(Nullable<System.DateTime>), false, false, true, false, (int)MatchToPlayRawFieldIndex.MatchDate, 0, 0, 0);
			this.AddElementFieldInfo("MatchToPlayRawTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)MatchToPlayRawFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits PlannedMatchView's info objects</summary>
		private void InitPlannedMatchTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PlannedMatchFieldIndex), "PlannedMatchTypedView");
			this.AddElementFieldInfo("PlannedMatchTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)PlannedMatchFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)PlannedMatchFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)PlannedMatchFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundLegSequenceNo", typeof(System.Int32), false, false, true, false, (int)PlannedMatchFieldIndex.RoundLegSequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("PlannedMatchTypedView", "RoundLegDescription", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.RoundLegDescription, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "HomeTeamId", typeof(System.Int64), false, false, true, false, (int)PlannedMatchFieldIndex.HomeTeamId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "HomeTeamNameForRound", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.HomeTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "GuestTeamId", typeof(System.Int64), false, false, true, false, (int)PlannedMatchFieldIndex.GuestTeamId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "GuestTeamNameForRound", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.GuestTeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "PlannedStart", typeof(Nullable<System.DateTime>), false, false, true, false, (int)PlannedMatchFieldIndex.PlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "PlannedEnd", typeof(Nullable<System.DateTime>), false, false, true, false, (int)PlannedMatchFieldIndex.PlannedEnd, 0, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "OrigPlannedStart", typeof(Nullable<System.DateTime>), false, false, true, false, (int)PlannedMatchFieldIndex.OrigPlannedStart, 0, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "OrigPlannedEnd", typeof(Nullable<System.DateTime>), false, false, true, false, (int)PlannedMatchFieldIndex.OrigPlannedEnd, 0, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)PlannedMatchFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "VenueName", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.VenueName, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "VenueExtension", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.VenueExtension, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "OrigVenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)PlannedMatchFieldIndex.OrigVenueId, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "OrigVenueName", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.OrigVenueName, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "OrigVenueExtension", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.OrigVenueExtension, 255, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "ChangeSerial", typeof(System.Int64), false, false, true, false, (int)PlannedMatchFieldIndex.ChangeSerial, 0, 0, 19);
			this.AddElementFieldInfo("PlannedMatchTypedView", "Remarks", typeof(System.String), false, false, true, false, (int)PlannedMatchFieldIndex.Remarks, 2147483647, 0, 0);
			this.AddElementFieldInfo("PlannedMatchTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)PlannedMatchFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RankingListView's info objects</summary>
		private void InitRankingListTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RankingListFieldIndex), "RankingListTypedView");
			this.AddElementFieldInfo("RankingListTypedView", "TournamentId", typeof(System.Int64), false, false, true, false, (int)RankingListFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("RankingListTypedView", "TournamentName", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.TournamentName, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "TournamentDescription", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.TournamentDescription, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "TournamentIsComplete", typeof(System.Boolean), false, false, true, false, (int)RankingListFieldIndex.TournamentIsComplete, 0, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)RankingListFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("RankingListTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)RankingListFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("RankingListTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "ClubName", typeof(System.String), false, false, true, false, (int)RankingListFieldIndex.ClubName, 255, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "ValuationDate", typeof(System.DateTime), false, false, true, false, (int)RankingListFieldIndex.ValuationDate, 0, 0, 0);
			this.AddElementFieldInfo("RankingListTypedView", "Rank", typeof(System.Int32), false, false, true, false, (int)RankingListFieldIndex.Rank, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "MatchPointsWon", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.MatchPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "MatchPointsLost", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.MatchPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "SetPointsWon", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.SetPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "SetPointsLost", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.SetPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "BallPointsWon", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.BallPointsWon, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "BallPointsLost", typeof(Nullable<System.Int32>), false, false, true, false, (int)RankingListFieldIndex.BallPointsLost, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "MatchesPlayed", typeof(System.Int32), false, false, true, false, (int)RankingListFieldIndex.MatchesPlayed, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "MatchesToPlay", typeof(System.Int32), false, false, true, false, (int)RankingListFieldIndex.MatchesToPlay, 0, 0, 10);
			this.AddElementFieldInfo("RankingListTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)RankingListFieldIndex.ModifiedOn, 0, 0, 0);
		}

		/// <summary>Inits RoundLegPeriodView's info objects</summary>
		private void InitRoundLegPeriodTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoundLegPeriodFieldIndex), "RoundLegPeriodTypedView");
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)RoundLegPeriodFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)RoundLegPeriodFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "LegId", typeof(System.Int64), false, false, true, false, (int)RoundLegPeriodFieldIndex.LegId, 0, 0, 19);
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "SequenceNo", typeof(System.Int32), false, false, true, false, (int)RoundLegPeriodFieldIndex.SequenceNo, 0, 0, 10);
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "StartDateTime", typeof(System.DateTime), false, false, true, false, (int)RoundLegPeriodFieldIndex.StartDateTime, 0, 0, 0);
			this.AddElementFieldInfo("RoundLegPeriodTypedView", "EndDateTime", typeof(System.DateTime), false, false, true, false, (int)RoundLegPeriodFieldIndex.EndDateTime, 0, 0, 0);
		}

		/// <summary>Inits RoundTeamView's info objects</summary>
		private void InitRoundTeamTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoundTeamFieldIndex), "RoundTeamTypedView");
			this.AddElementFieldInfo("RoundTeamTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)RoundTeamFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("RoundTeamTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)RoundTeamFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamClubName", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.TeamClubName, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamMatchDayOfWeek", typeof(Nullable<System.Int32>), false, false, true, false, (int)RoundTeamFieldIndex.TeamMatchDayOfWeek, 0, 0, 10);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamMatchTime", typeof(Nullable<System.TimeSpan>), false, false, true, false, (int)RoundTeamFieldIndex.TeamMatchTime, 0, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamPhoto", typeof(System.String), false, false, true, false, (int)RoundTeamFieldIndex.TeamPhoto, 255, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TeamModifiedOn", typeof(System.DateTime), false, false, true, false, (int)RoundTeamFieldIndex.TeamModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("RoundTeamTypedView", "TournamentId", typeof(System.Int64), false, false, true, false, (int)RoundTeamFieldIndex.TournamentId, 0, 0, 19);
		}

		/// <summary>Inits TeamUserRoundView's info objects</summary>
		private void InitTeamUserRoundTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TeamUserRoundFieldIndex), "TeamUserRoundTypedView");
			this.AddElementFieldInfo("TeamUserRoundTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)TeamUserRoundFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "MatchDayOfWeek", typeof(Nullable<System.Int32>), false, false, true, false, (int)TeamUserRoundFieldIndex.MatchDayOfWeek, 0, 0, 10);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "MatchWeekday", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.MatchWeekday, 4000, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "MatchTime", typeof(Nullable<System.TimeSpan>), false, false, true, false, (int)TeamUserRoundFieldIndex.MatchTime, 0, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "ClubName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.ClubName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "PhotoFilename", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.PhotoFilename, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "TeamModifiedOn", typeof(System.DateTime), false, false, true, false, (int)TeamUserRoundFieldIndex.TeamModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "UserId", typeof(System.Int64), false, false, true, false, (int)TeamUserRoundFieldIndex.UserId, 0, 0, 19);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "Gender", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.Gender, 1, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "Title", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.Title, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "FirstName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.FirstName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "MiddleName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.MiddleName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "LastName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.LastName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "Nickname", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.Nickname, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "PhoneNumber", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.PhoneNumber, 40, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "PhoneNumber2", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.PhoneNumber2, 40, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "Email", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.Email, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "Email2", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.Email2, 100, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "UserModifiedOn", typeof(System.DateTime), false, false, true, false, (int)TeamUserRoundFieldIndex.UserModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "IsManager", typeof(System.Boolean), false, false, true, false, (int)TeamUserRoundFieldIndex.IsManager, 0, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "IsPlayer", typeof(System.Boolean), false, false, true, false, (int)TeamUserRoundFieldIndex.IsPlayer, 0, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)TeamUserRoundFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)TeamUserRoundFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("TeamUserRoundTypedView", "TournamentId", typeof(Nullable<System.Int64>), false, false, true, false, (int)TeamUserRoundFieldIndex.TournamentId, 0, 0, 19);
		}

		/// <summary>Inits TeamVenueRoundView's info objects</summary>
		private void InitTeamVenueRoundTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(TeamVenueRoundFieldIndex), "TeamVenueRoundTypedView");
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamClubName", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamClubName, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamPhoto", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamPhoto, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "MatchDayOfWeek", typeof(Nullable<System.Int32>), false, false, true, false, (int)TeamVenueRoundFieldIndex.MatchDayOfWeek, 0, 0, 10);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "MatchWeekday", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.MatchWeekday, 4000, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "MatchTime", typeof(Nullable<System.TimeSpan>), false, false, true, false, (int)TeamVenueRoundFieldIndex.MatchTime, 0, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TeamModifiedOn", typeof(System.DateTime), false, false, true, false, (int)TeamVenueRoundFieldIndex.TeamModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueId", typeof(Nullable<System.Int64>), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueName", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueName, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueStreet", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueStreet, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenuePostalCode", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenuePostalCode, 10, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueCity", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueCity, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueDirection", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueDirection, 2147483647, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueLongitude", typeof(Nullable<System.Double>), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueLongitude, 0, 0, 38);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueLatitude", typeof(Nullable<System.Double>), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueLatitude, 0, 0, 38);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenuePrecisePosition", typeof(Nullable<System.Boolean>), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenuePrecisePosition, 0, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "VenueModifiedOn", typeof(Nullable<System.DateTime>), false, false, true, false, (int)TeamVenueRoundFieldIndex.VenueModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)TeamVenueRoundFieldIndex.RoundId, 0, 0, 19);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "RoundName", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.RoundName, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "RoundDescription", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.RoundDescription, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "RoundTypeName", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.RoundTypeName, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "RoundTypeDescription", typeof(System.String), false, false, true, false, (int)TeamVenueRoundFieldIndex.RoundTypeDescription, 255, 0, 0);
			this.AddElementFieldInfo("TeamVenueRoundTypedView", "TournamentId", typeof(System.Int64), false, false, true, false, (int)TeamVenueRoundFieldIndex.TournamentId, 0, 0, 19);
		}

		/// <summary>Inits VenueDistanceResultView's info objects</summary>
		private void InitVenueDistanceResultTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VenueDistanceResultFieldIndex), "VenueDistanceResultTypedView");
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Id", typeof(System.Int64), false, false, true, false, (int)VenueDistanceResultFieldIndex.Id, 0, 0, 19);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Name", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Extension", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.Extension, 255, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Street", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.Street, 255, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "PostalCode", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.PostalCode, 10, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "City", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Longitude", typeof(Nullable<System.Double>), false, false, true, false, (int)VenueDistanceResultFieldIndex.Longitude, 0, 0, 15);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Latitude", typeof(Nullable<System.Double>), false, false, true, false, (int)VenueDistanceResultFieldIndex.Latitude, 0, 0, 15);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "PrecisePosition", typeof(System.Boolean), false, false, true, false, (int)VenueDistanceResultFieldIndex.PrecisePosition, 0, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Direction", typeof(System.String), false, false, true, false, (int)VenueDistanceResultFieldIndex.Direction, 2147483647, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "CreatedOn", typeof(System.DateTime), false, false, true, false, (int)VenueDistanceResultFieldIndex.CreatedOn, 0, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "ModifiedOn", typeof(System.DateTime), false, false, true, false, (int)VenueDistanceResultFieldIndex.ModifiedOn, 0, 0, 0);
			this.AddElementFieldInfo("VenueDistanceResultTypedView", "Distance", typeof(System.Double), false, false, true, false, (int)VenueDistanceResultFieldIndex.Distance, 0, 0, 15);
		}

		/// <summary>Inits VenueTeamView's info objects</summary>
		private void InitVenueTeamTypedViewInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(VenueTeamFieldIndex), "VenueTeamTypedView");
			this.AddElementFieldInfo("VenueTeamTypedView", "VenueId", typeof(System.Int64), false, false, true, false, (int)VenueTeamFieldIndex.VenueId, 0, 0, 19);
			this.AddElementFieldInfo("VenueTeamTypedView", "VenueName", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.VenueName, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "VenueExtension", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.VenueExtension, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "Street", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.Street, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "PostalCode", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.PostalCode, 10, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "City", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.City, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "Direction", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.Direction, 2147483647, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "Longitude", typeof(Nullable<System.Double>), false, false, true, false, (int)VenueTeamFieldIndex.Longitude, 0, 0, 38);
			this.AddElementFieldInfo("VenueTeamTypedView", "Latitude", typeof(Nullable<System.Double>), false, false, true, false, (int)VenueTeamFieldIndex.Latitude, 0, 0, 38);
			this.AddElementFieldInfo("VenueTeamTypedView", "PrecisePosition", typeof(System.Boolean), false, false, true, false, (int)VenueTeamFieldIndex.PrecisePosition, 0, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "TeamId", typeof(System.Int64), false, false, true, false, (int)VenueTeamFieldIndex.TeamId, 0, 0, 19);
			this.AddElementFieldInfo("VenueTeamTypedView", "TeamName", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.TeamName, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "TeamNameForRound", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.TeamNameForRound, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "TeamClubName", typeof(System.String), false, false, true, false, (int)VenueTeamFieldIndex.TeamClubName, 255, 0, 0);
			this.AddElementFieldInfo("VenueTeamTypedView", "TournamentId", typeof(System.Int64), false, false, true, false, (int)VenueTeamFieldIndex.TournamentId, 0, 0, 19);
			this.AddElementFieldInfo("VenueTeamTypedView", "RoundId", typeof(System.Int64), false, false, true, false, (int)VenueTeamFieldIndex.RoundId, 0, 0, 19);
		}
	}
}